version: '3'

services:
  pokedoc-app:
    image: pokedoc-app
    ports:
      - '9000:9000'
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: pokedoc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:
  
  